server: 
  port: 8001
  
spring: 
  application: 
    name: buyer-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart_product?useUnicode=true&characterEncoding=utf8
    username: root
    password: 
    initialization-mode: never
    druid:
      initial-size: 5 
      min-idle: 10 
      max-active: 20 
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com:
      ibm:
        fsd:
          mod: debug