pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
            // clone
            git 'https://github.com/lx-emart/emart-project.git'
            // build
            bat '''
                   CD emart-project
                   CD emart-all
                   CD zuul-server
                   mvn -Dmaven.test.failure.ignore=true clean package
                '''
         }

         post {
            success {
               archiveArtifacts 'emart-project/emart-all/zuul-server/target/*.jar'
            }
         }
      }
      
      stage('Deploy') {
         steps {
            bat '''
                 CD emart-project
                 CD emart-all
                 CD zuul-server
                 docker build -t zuul-server .
                 
            '''
         }

         post {
            success {
               bat 'docker run -d -p 8889:8080 zuul-server'
            }
         }
      }
      
   }
}
