pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
            // clone
            git 'https://github.com/lx-emart/emart-project.git'
            // build
            bat '''
                   CD emart-project
                   CD emart-all
                   CD user-api
                   mvn -Dmaven.test.failure.ignore=true clean package
                '''
         }

         post {
            success {
               archiveArtifacts 'emart-project/emart-all/user-api/target/*.jar'
            }
         }
      }
      
      stage('Deploy') {
         steps {
            bat '''
                 CD emart-project
                 CD emart-all
                 CD user-api
                 docker build -t user-api .
                 
            '''
         }

         post {
            success {
               bat 'docker run -d -p 7001:7001 user-api'
            }
         }
      }
      
   }
}
